spring:
  config:
    activate:
      on-profile: datasource

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${rdb-url}:${rdb-port}/${rdb-database}
    username: ${rdb-user}
    password: ${rdb-password}
    hikari:
      maximum-pool-size: 10
      max-lifetime: 28500000 #DB WAIT_TIMEOUT -> 28800 (28800000)

  elasticsearch:
    uris: ${es-url}:${es-port}
    username: ${es-user}
    password: ${es-password}

  data:
    redis:
      host: ${redis-host}
      port: ${redis-port}
      database: ${redis-database} # 기본: 0
      username: ${redis-user} # 공백으로 생략 가능
      password: ${redis-password} # 공백으로 생략 가능
  cache:
    type: redis # cache 사용시, 선택적
    redis:
      time-to-live: 6000000 #(ms) # 만료없음: -1

  mail:
    host: ${email-host} #smtp.gmail.com #smtp.naver.com
    port: ${email-port} #587
    username: ${email-user} #your.email@gmail.com #yourid@naver.com
    password: ${email-password} #your-app-password #your-password #구글은 계정 비밀번호 말고 앱 비밀번호를 발급받아 사용해야함
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true